version: '3.7'

volumes:
  backend-data:
  db:
  db_ca:
  db_reg:
  data_es:
  data_es_test:

services:
  proxy:
    image: unicef/hct-mis-proxy
    environment:
      - DJANGO_APPLICATION_SERVICE_HOST=backend
      - FRONTEND_HOST=host.docker.internal:3000
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - backend
    volumes:
      - backend-data:/data

  redis:
    restart: always
    image: redis:4.0.11-alpine3.8
    expose:
      - "6379"

  backend:
    stdin_open: true
    tty: true
    image: unicef/hct-mis-backend
    env_file:
      - .env
    environment:
      - REDIS_INSTANCE=redis:6379
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        APP_ENV: DEV
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/code/
      - backend-data:/data
    command: "dev"
    depends_on:
      - db
      - redis
      - cash_assist_datahub_db
      - registration_datahub_db
      - elasticsearch
      - elasticsearch_test

  celery_worker:
    stdin_open: true
    tty: true
    image: unicef/hct-mis-backend
    env_file:
      - .env
    environment:
      - REDIS_INSTANCE=redis:6379
    volumes:
      - ./backend:/code/
      - backend-data:/data
    restart: always
    command: "watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A hct_mis_api.apps.core.celery worker -E -l info"
    depends_on:
      - backend
      - db
      - redis
      - cash_assist_datahub_db
      - registration_datahub_db
      - elasticsearch
      - elasticsearch_test

  celery-beat:
    stdin_open: true
    tty: true
    image: unicef/hct-mis-backend
    env_file:
      - .env
    environment:
      - REDIS_INSTANCE=redis:6379
    volumes:
      - ./backend:/code/
      - backend-data:/data
    restart: always
    command: "celery -A hct_mis_api.apps.core.celery beat -l INFO"
    depends_on:
      - backend
      - db
      - redis
      - cash_assist_datahub_db
      - registration_datahub_db
      - elasticsearch
      - elasticsearch_test

  celery-flower:
    image: saxix/flower:1.6
    command: ["flower", "--broker=redis://redis:6379/0", "--port=5555"]
    environment:
      - FLOWER_AUTH_PROVIDER=""
      - FLOWER_DEBUG="1"
      - FLOWER_ADDRESS=0.0.0.0
    ports:
      - "5555:5555"
    restart: always
    depends_on:
      - redis

  db:
    image: mdillon/postgis:9.5-alpine
    volumes:
      - db:/data/postgres
    env_file:
      - .env

  cash_assist_datahub_db:
    image: mdillon/postgis:9.5-alpine
    volumes:
      - db_ca:/data/postgres
    env_file:
      - .env
    ports:
      - "5433:5432"

  registration_datahub_db:
    image: mdillon/postgis:9.5-alpine
    volumes:
      - db_reg:/data/postgres
    env_file:
      - .env

  elasticsearch:
    image: unicef/hct-elasticsearch
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data_es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  elasticsearch_test:
    image: unicef/hct-elasticsearch-test
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster-test
      - cluster.initial_master_nodes=es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data_es_test:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
