apiVersion: v1
kind: ConfigMap
metadata:
  name: hope-airflow-extra
  labels:
    {{- include "hope.labels" . | nindent 4 }}
data:
  {{- include "hope.postgresql.config" . | nindent 2}}
  {{- include "hope.postgresql.airflow.config" . | nindent 2}}
  {{- include "hope.registrationdatahubpostgresql.config" . | nindent 2}}
  {{- include "hope.cashassistdatahubpostgresql.config" . | nindent 2}}
  {{- include "hope.elasticsearch.config" . | nindent 2}}
  DJANGO_ALLOWED_HOSTS: "{{.Values.ingress.host }},kubernetes.internal"
  DOMAIN: {{.Values.ingress.host }}
  ENV: {{ .Values.global.env }}
  REDIS_INSTANCE: hope-main-redis-master
  C_FORCE_ROOT: "1"
  AIRFLOW__CORE__BROKER_URL: redis://hope-main-redis-master:6379/0
  AIRFLOW__CELERY__BROKER_URL: redis://hope-main-redis-master:6379/0
{{- range $key, $value :=  .Values.backend.config }}
  {{ if eq $value "" }}
  {{ else }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hope-airflow-entrypoint
  labels:
    {{- include "hope.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/airflow-entrypoint.sh").AsConfig | indent 2 }}
