apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hope.fullname" . }}-job-backend
  labels:
    {{- include "hope.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
data:
  {{- include "hope.postgresql.config" . | nindent 2}}
  {{- include "hope.registrationdatahubpostgresql.config" . | nindent 2}}
  {{- include "hope.cashassistdatahubpostgresql.config" . | nindent 2}}
  {{- include "hope.elasticsearch.config" . | nindent 2}}
  DJANGO_ALLOWED_HOSTS: "{{.Values.ingress.host }},kubernetes.internal"
  DOMAIN: {{.Values.ingress.host }}
  ENV: {{ .Values.global.env }}
  REDIS_INSTANCE: hope-main-redis-master
  FLOWER_BROKER_API: redis://hope-main-redis-master:6379/0
{{- range $key, $value :=  .Values.backend.config }}
  {{- if eq $value "" }}
  {{- else }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
