apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hope.fullname" . }}-backend
  labels:
    {{- include "hope.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value :=  .Values.backend.secret }}
{{- if eq "bool" (typeOf $value) }}
{{- $stringValue := $value | toString }}
  {{ $key }}: {{ $stringValue | b64enc | quote }}
{{- else }}
  {{- if eq $value "" }}
  {{- else }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
