version: '3.7'

volumes:
  backend-data:
  db:
  db_ca:
  db_reg:
  db_airflow:
  airflow:
  data_es:
  data_es_test:

services:

  redis:
    restart: always
    image: redis:4.0.11-alpine3.8
    expose:
      - "6379"

  backend:
    stdin_open: true
    tty: true
    image: ${backend_image}
    env_file:
      - .env
    environment:
      - REDIS_INSTANCE=redis:6379
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/code/
      - backend-data:/data
    # FIXME: I know that links are deprecated
    links:
      - airflow_webserver
    command: "dev"
    depends_on:
      - db
      - redis
      - cash_assist_datahub_db
      - registration_datahub_db
      - elasticsearch_test
  db:
    image: mdillon/postgis:9.5-alpine
    volumes:
      - db:/data/postgres
    env_file:
      - .env

  cash_assist_datahub_db:
    image: mdillon/postgis:9.5-alpine
    volumes:
      - db_ca:/data/postgres
    env_file:
      - .env
    ports:
      - "5433:5432"

  registration_datahub_db:
    image: mdillon/postgis:9.5-alpine
    volumes:
      - db_reg:/data/postgres
    env_file:
      - .env

  airflow_db:
    image: postgres:9.5.15-alpine
    volumes:
      - db_airflow:/data/postgres
    env_file:
      - ./airflow/config/.env_airflow

  airflow_webserver:
    image: ${airflow_image}
    ports:
      - "4200:8080"
    env_file:
      - ./airflow/config/.env_airflow
    restart: always
    depends_on:
      - airflow_db
      - db
      - registration_datahub_db
      - cash_assist_datahub_db
      - airflow_worker
      - redis
    links:
      - airflow_worker
    volumes:
      - ./airflow/connectors:/usr/local/airflow/connectors
      - ./airflow/dags:/usr/local/airflow/dags
      - ./backend:/usr/local/airflow/backend
      - backend-data:/usr/local/airflow/data
    command: webserver
    logging:  #NOTE: noisy output silenced
      driver: "none"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  airflow_flower:
    image: ${airflow_image}
    restart: always
    depends_on:
      - airflow_db
      - redis
    volumes:
      - ./airflow/connectors:/usr/local/airflow/connectors
      - ./airflow/dags:/usr/local/airflow/dags
      - ./backend:/usr/local/airflow/backend
      - backend-data:/usr/local/airflow/data
    env_file:
      - ./airflow/config/.env_airflow
    ports:
      - "5555:5555"
    command: flower

  airflow_scheduler:
    image: ${airflow_image}
    env_file:
      - ./airflow/config/.env_airflow
    restart: always
    volumes:
      - ./airflow/connectors:/usr/local/airflow/connectors
      - ./airflow/dags:/usr/local/airflow/dags
      - ./backend:/usr/local/airflow/backend
      - backend-data:/usr/local/airflow/data
    command: scheduler
    logging:  #NOTE: noisy output silenced
      driver: "none"
    depends_on:
      - airflow_webserver
      - airflow_db

  airflow_worker:
    image: ${airflow_image}
    env_file:
      - ./airflow/config/.env_airflow
    restart: always
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/connectors:/usr/local/airflow/connectors
      - ./backend:/usr/local/airflow/backend
      - backend-data:/usr/local/airflow/data
    command: worker

  elasticsearch_test:
    image: unicef/hct-elasticsearch-test
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster-test
      - cluster.initial_master_nodes=es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data_es_test:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
