global:
  env: staging
  storageClass: default

backend:
  image: #from-pipeline
  replicaCount: 1
  config:
    POSTGRES_SSL: "true"
    STORAGE_AZURE_ACCOUNT_NAME: hctmisdev
    EMAIL_HOST: "extmail01.unicef.org"
    EMAIL_USE_TLS: "false"
    KOBO_KF_URL: "https://kobo.humanitarianresponse.info"
    KOBO_KC_URL: "https://kobo.humanitarianresponse.info"
  secret:
    AZURE_CLIENT_ID: #secret-variables: AZURE_CLIENT_ID
    AZURE_CLIENT_SECRET: #secret-variables: AZURE_CLIENT_SECRET
    AZURE_TENANT_KEY: #secret-variables: AZURE_TENANT_KEY
    STORAGE_AZURE_ACCOUNT_KEY: #secret-variables: STORAGE_AZURE_ACCOUNT_KEY
    SECRET_KEY: #secret-variables: SECRET_KEY
    SENTRY_DSN: #secret-variables: SENTRY_DSN
    KOBO_APP_API_TOKEN: #secret-variables: KOBO_APP_API_TOKEN
    EXCHANGE_RATES_API_KEY: #secret-variables: EXCHANGE_RATES_API_KEY
    ROOT_ACCESS_TOKEN: #secret-variables: ROOT_ACCESS_TOKEN

frontend:
  image: #from-pipeline

celery:
  image: #from-pipeline
  replicaCount: 1

celeryflower:
  secret:
    FLOWER_BASIC_AUTH: #secret-variables: FLOWER_BASIC_AUTH

ingress:
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: kv-cert-unitst
  host: dev-hope.unitst.org


postgresql:
  host: pgsql-14-reserved-hctmis-devstg.postgres.database.azure.com
  username: devcashubusr
  password: #secret-variables: POSTGRES_PASSWORD
  database: dev_hope_appdb_datahubdb
registrationdatahubpostgresql:
  host: pgsql-14-reserved-hctmis-devstg.postgres.database.azure.com
  username: devreghubusr
  password: #secret-variables: REGISTRATION_DATAHUB_POSTGRES_PASSWORD
  database: dev_registration_datahubdb
cashassistdatahubpostgresql:
  host: pgsql-14-reserved-hctmis-devstg.postgres.database.azure.com
  username: devcashubusr
  password: #secret-variables: CASH_ASSIST_DATAHUB_POSTGRES_PASSWORD
  database: dev_cashassist_datahubdb
