---
kind: Service
apiVersion: v1
metadata:
    name: frontend
    annotations:
        revision: "{{CF_SHORT_REVISION}}"
    namespace: {{NAMESPACE}}
spec:
    ports:
        -   protocol: TCP
            port: 8080
    type: NodePort
    selector:
        app: frontend-container
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: frontend
    labels:
        app: frontend
    annotations:
        revision: "{{CF_SHORT_REVISION}}"
    namespace: {{NAMESPACE}}
spec:
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1
    replicas: 1
    selector:
        matchLabels:
            app: frontend-container
    template:
        metadata:
            labels:
                app: frontend-container
        spec:
            containers:
                -   name: frontend
                    image: unicef/hct-mis-frontend:{{CF_SHORT_REVISION}}
                    command: ["bash"]
                    args: ["-c", "/./entrypoint.sh"]
                    env:
                        -   name: MAP_BOX_KEY
                            value: {{MAP_BOX_KEY}}
                    readinessProbe:
                        httpGet:
                            path: /
                            port: 8080
                        initialDelaySeconds: 5
                        periodSeconds: 5
                        successThreshold: 1
