revision: 1
namespace: staging
env:
domain: 

backend:
  image:
  maxUnavilable: 0
  maxSurge: 1
  replicas: 1
  port: 8000
  healthCheckPath: "/api/_health"
  secret:
    SECRET_KEY: ""
    POSTGRES_DB: ""
    POSTGRES_USER: ""
    POSTGRES_PASSWORD: ""
    POSTGRES_HOST: "backend-db"
    POSTGRES_CASHASSIST_DATAHUB_DB: ""
    POSTGRES_CASHASSIST_DATAHUB_USER: ""
    POSTGRES_CASHASSIST_DATAHUB_PASSWORD: ""
    POSTGRES_CASHASSIST_DATAHUB_HOST: "postgres-cash-assist-datahub-db"
    POSTGRES_REGISTRATION_DATAHUB_DB: ""
    POSTGRES_REGISTRATION_DATAHUB_USER: ""
    POSTGRES_REGISTRATION_DATAHUB_PASSWORD: ""
    POSTGRES_REGISTRATION_DATAHUB_HOST: "registration-datahub-db"
    DJANGO_ALLOWED_HOST: ""
    DOMAIN: ""
    ENV: ""
    AZURE_CLIENT_ID: ""
    AZURE_CLIENT_SECRET: ""
    AZURE_TENANT_KEY: ""
    NEW_ENV: ""
  staticStorage:
    secretName: ""
    accountName: ""

frontend:
  image:
  maxUnavilable: 0
  maxSurge: 1
  replicas: 1
  port: 80

redis:
  image: redis
  port: 6379


databases:
  postgres-cash-assist-datahub-db:
    image: mdillon/postgis:10-alpine
    port: 5432
    secret:
      POSTGRES_DB: ""
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
  backend-db:
    image: mdillon/postgis:10-alpine
    port: 5432
    secret:
      POSTGRES_DB: ""
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
  registration-datahub-db:
    image: mdillon/postgis:10-alpine
    port: 5432
    secret:
      POSTGRES_DB: ""
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
